import pandas as pd
df0 = pd.read_csv("weather-splitted/dataset_station1_STATION_0.csv")
df1 = pd.read_csv("weather-splitted/dataset_station1_STATION_1.csv")
df2 = pd.read_csv("weather-splitted/dataset_station1_STATION_2.csv")
df3 = pd.read_csv("weather-splitted/dataset_station1_STATION_3.csv")
df4 = pd.read_csv("weather-splitted/dataset_station1_STATION_4.csv")
df5 = pd.read_csv("weather-splitted/dataset_station1_STATION_5.csv")
df6 = pd.read_csv("weather-splitted/dataset_station1_STATION_6.csv")
df7 = pd.read_csv("weather-splitted/dataset_station1_STATION_7.csv")
df8 = pd.read_csv("weather-splitted/dataset_station1_STATION_8.csv")
df9 = pd.read_csv("weather-splitted/dataset_station1_STATION_9.csv")
df10 = pd.read_csv("weather-splitted/dataset_station1_STATION_10.csv")
df11 = pd.read_csv("weather-splitted/dataset_station1_STATION_11.csv")
df12 = pd.read_csv("weather-splitted/dataset_station1_STATION_12.csv")
df13 = pd.read_csv("weather-splitted/dataset_station1_STATION_13.csv")

df15 = pd.read_csv("weather-splitted/dataset_station1_STATION_15.csv")

df17 = pd.read_csv("weather-splitted/dataset_station1_STATION_17.csv")
df18 = pd.read_csv("weather-splitted/dataset_station1_STATION_18.csv")
df19 = pd.read_csv("weather-splitted/dataset_station1_STATION_19.csv")
df20 = pd.read_csv("weather-splitted/dataset_station1_STATION_20.csv")
df21 = pd.read_csv("weather-splitted/dataset_station1_STATION_21.csv")
df22 = pd.read_csv("weather-splitted/dataset_station1_STATION_22.csv")
df23 = pd.read_csv("weather-splitted/dataset_station1_STATION_23.csv")

df25 = pd.read_csv("weather-splitted/dataset_station1_STATION_25.csv")
df26 = pd.read_csv("weather-splitted/dataset_station1_STATION_26.csv")
df27 = pd.read_csv("weather-splitted/dataset_station1_STATION_27.csv")
df28 = pd.read_csv("weather-splitted/dataset_station1_STATION_28.csv")
df29 = pd.read_csv("weather-splitted/dataset_station1_STATION_29.csv")
df30 = pd.read_csv("weather-splitted/dataset_station1_STATION_30.csv")
df31 = pd.read_csv("weather-splitted/dataset_station1_STATION_31.csv")

df33 = pd.read_csv("weather-splitted/dataset_station1_STATION_33.csv")
df34 = pd.read_csv("weather-splitted/dataset_station1_STATION_34.csv")
df35 = pd.read_csv("weather-splitted/dataset_station1_STATION_35.csv")
df36 = pd.read_csv("weather-splitted/dataset_station1_STATION_36.csv")
df37 = pd.read_csv("weather-splitted/dataset_station1_STATION_37.csv")
df38 = pd.read_csv("weather-splitted/dataset_station1_STATION_38.csv")
df39 = pd.read_csv("weather-splitted/dataset_station1_STATION_39.csv")
df40 = pd.read_csv("weather-splitted/dataset_station1_STATION_40.csv")
df41 = pd.read_csv("weather-splitted/dataset_station1_STATION_41.csv")
df42 = pd.read_csv("weather-splitted/dataset_station1_STATION_42.csv")
df43 = pd.read_csv("weather-splitted/dataset_station1_STATION_43.csv")
df44 = pd.read_csv("weather-splitted/dataset_station1_STATION_44.csv")

df46 = pd.read_csv("weather-splitted/dataset_station1_STATION_46.csv")
df47 = pd.read_csv("weather-splitted/dataset_station1_STATION_47.csv")
df48 = pd.read_csv("weather-splitted/dataset_station1_STATION_48.csv")
df49 = pd.read_csv("weather-splitted/dataset_station1_STATION_49.csv")
df50 = pd.read_csv("weather-splitted/dataset_station1_STATION_50.csv")
df51 = pd.read_csv("weather-splitted/dataset_station1_STATION_51.csv")
df52 = pd.read_csv("weather-splitted/dataset_station1_STATION_52.csv")

df54 = pd.read_csv("weather-splitted/dataset_station1_STATION_54.csv")
df55 = pd.read_csv("weather-splitted/dataset_station1_STATION_55.csv")
df56 = pd.read_csv("weather-splitted/dataset_station1_STATION_56.csv")
df57 = pd.read_csv("weather-splitted/dataset_station1_STATION_57.csv")
df58 = pd.read_csv("weather-splitted/dataset_station1_STATION_58.csv")
df59 = pd.read_csv("weather-splitted/dataset_station1_STATION_59.csv")
df60 = pd.read_csv("weather-splitted/dataset_station1_STATION_60.csv")
df61 = pd.read_csv("weather-splitted/dataset_station1_STATION_61.csv")
df62 = pd.read_csv("weather-splitted/dataset_station1_STATION_62.csv")
df63 = pd.read_csv("weather-splitted/dataset_station1_STATION_63.csv")
df64 = pd.read_csv("weather-splitted/dataset_station1_STATION_64.csv")

df66 = pd.read_csv("weather-splitted/dataset_station1_STATION_66.csv")
df67 = pd.read_csv("weather-splitted/dataset_station1_STATION_67.csv")
df68 = pd.read_csv("weather-splitted/dataset_station1_STATION_68.csv")
df69 = pd.read_csv("weather-splitted/dataset_station1_STATION_69.csv")
df70 = pd.read_csv("weather-splitted/dataset_station1_STATION_70.csv")
df71 = pd.read_csv("weather-splitted/dataset_station1_STATION_71.csv")
df72 = pd.read_csv("weather-splitted/dataset_station1_STATION_72.csv")
df73 = pd.read_csv("weather-splitted/dataset_station1_STATION_73.csv")
df74 = pd.read_csv("weather-splitted/dataset_station1_STATION_74.csv")
df75 = pd.read_csv("weather-splitted/dataset_station1_STATION_75.csv")
df76 = pd.read_csv("weather-splitted/dataset_station1_STATION_76.csv")
df77 = pd.read_csv("weather-splitted/dataset_station1_STATION_77.csv")
df78 = pd.read_csv("weather-splitted/dataset_station1_STATION_78.csv")
df79 = pd.read_csv("weather-splitted/dataset_station1_STATION_79.csv")
df80 = pd.read_csv("weather-splitted/dataset_station1_STATION_80.csv")
df81 = pd.read_csv("weather-splitted/dataset_station1_STATION_81.csv")
df82 = pd.read_csv("weather-splitted/dataset_station1_STATION_82.csv")
df83 = pd.read_csv("weather-splitted/dataset_station1_STATION_83.csv")
df84 = pd.read_csv("weather-splitted/dataset_station1_STATION_84.csv")
df85 = pd.read_csv("weather-splitted/dataset_station1_STATION_85.csv")
df86 = pd.read_csv("weather-splitted/dataset_station1_STATION_86.csv")
df87 = pd.read_csv("weather-splitted/dataset_station1_STATION_87.csv")
df88 = pd.read_csv("weather-splitted/dataset_station1_STATION_88.csv")
df89 = pd.read_csv("weather-splitted/dataset_station1_STATION_89.csv")

dataset = pd.concat([df0,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df15,df17,df18,df19,df20,df21,df22,df23,df25,df26,df27,df28,df29,df30,df31,df33,df34,df35,df36,df37,df38,df39,df40,df41,df42,df43,df44,df46,df47,df48,df49,df50,df51,df52,df54,df55,df56,df57,df58,df59,df60,df61,df62,df63,df64,df66,df67,df68,df69,df70,df71,df72,df73,df74,df75,df76,df77,df78,df79,df80,df81,df82,df83,df84,df85,df86,df87,df88,df89])

dataset.to_csv('dataset-station.csv')